-- Steve's Car Showroom
-- QUESTIONS

-- 1. What are the details of all cars purchased in the year 2022?
SELECT cars.*,
        purchase_date
FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
WHERE EXTRACT(YEAR FROM purchase_date) = 2022
ORDER BY car_id;

| car_id | make       | type    | style    | cost_$ | purchase_date |
|--------|------------|---------|----------|--------|----------------|
| 9      | Honda      | Civic   | Sedan    | 30000  | 2022-01-01     |
| 10     | Toyota     | Corolla | Hatchback| 25000  | 2022-02-03     |
| 11     | Mercedes   | C-Class | Coupe    | 60000  | 2022-02-10     |
| 12     | Audi       | A4      | Sedan    | 48000  | 2022-03-01     |
| 13     | BMW        | X5      | SUV      | 55000  | 2022-04-02     |
| 14     | Ford       | Explorer| SUV      | 40000  | 2022-05-05     |
| 15     | BMW        | X5      | SUV      | 55000  | 2022-06-07     |
| 16     | Toyota     | Corolla | Hatchback| 25000  | 2022-07-09     |

-- 2. What is the total number of cars sold by each salesperson?
SELECT name AS salesperson,
        COUNT(car_id) AS num_of_cars_sold
FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
GROUP BY name
ORDER BY num_of_cars_sold DESC;

-- 3. What is the total revenue generated by each salesperson?
SELECT name AS salesperson,
        SUM(cost_$) AS total_revenue
FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
INNER JOIN cars ON sales.car_id = cars.car_id
GROUP BY name
ORDER BY total_revenue DESC;

-- 4. What are the details of the cars sold by each salesperson?
SELECT DISTINCT name AS salesperson,
        cars.*
FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
INNER JOIN cars ON sales.car_id = cars.car_id
ORDER BY salesperson, car_id;

-- 5. What is the total revenue generated by each car type?
SELECT cars.type,
        SUM(cost_$) AS total_revenue
FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
GROUP BY cars.type
ORDER BY total_revenue DESC;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
WITH filtered_sales AS (
    SELECT car_id
    FROM sales
    WHERE salesman_id IN (SELECT salesman_id FROM salespersons WHERE name = 'Emily Wong')
        AND EXTRACT(YEAR FROM purchase_date) = 2021
)
SELECT DISTINCT cars.*
FROM cars
WHERE car_id IN (SELECT car_id FROM filtered_sales)
ORDER BY car_id;

-- 7. What is the total revenue generated by the sales of hatchback cars?
WITH hatchback_cars AS (
    SELECT car_id, cost_$
    FROM cars
    WHERE style = 'Hatchback'
)
SELECT SUM(cost_$) AS total_revenue_hatchback_cars
FROM sales
INNER JOIN hatchback_cars ON sales.car_id = hatchback_cars.car_id;

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT SUM(cost_$) AS total_revenue_SUV_2022
FROM cars
WHERE car_id IN (SELECT car_id FROM sales WHERE EXTRACT(YEAR FROM purchase_date) = 2022)
    AND style = 'SUV';

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
WITH best_salesman_2023 AS (
    SELECT salesman_id,
    COUNT(car_id) AS num_of_cars_sold_2023
    FROM sales
    WHERE EXTRACT(YEAR FROM purchase_date) = 2023
    GROUP BY salesman_id
    ORDER BY num_of_cars_sold_2023 DESC
    LIMIT 1
)
SELECT name AS salesperon,
    city
FROM salespersons
WHERE salesman_id IN (SELECT salesman_id FROM best_salesman_2023);

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
WITH sales_2022 AS (
    SELECT salesman_id,
        car_id
    FROM sales
    WHERE EXTRACT(YEAR FROM purchase_date) = 2022
),
cars_2022 AS (
    SELECT salesman_id,
        SUM(cost_$) AS total_revenue
    FROM sales_2022
    LEFT JOIN cars ON sales_2022.car_id = cars.car_id
    GROUP BY salesman_id
    ORDER BY total_revenue DESC
    LIMIT 1
)
SELECT name AS salesperson,
    age
FROM salespersons
WHERE salesman_id IN (SELECT salesman_id FROM cars_2022)
