-- Challenge 1 - Steve's Car Showroom

-- QUESTIONS

-- 1. What are the details of all cars purchased in the year 2022?
SELECT cars.*,
        purchase_date
FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
WHERE EXTRACT(YEAR FROM purchase_date) = 2022
ORDER BY car_id;

-- Sol1:
| car_id | make       | type    | style    | cost_$ | purchase_date |
|--------|------------|---------|----------|--------|----------------|
| 1      | Honda      | Civic   | Sedan    | 30000  | 2022-07-09     |
| 1      | Honda      | Civic   | Sedan    | 30000  | 2022-02-03     |
| 2      | Toyota     | Corolla | Hatchback| 25000  | 2022-01-01     |
| 3      | Ford       | Explorer| SUV      | 40000  | 2022-05-05     |
| 5      | BMW        | X5      | SUV      | 55000  | 2022-06-07     |
| 5      | BMW        | X5      | SUV      | 55000  | 2022-04-02     |
| 7      | Mercedes   | C-Class | Coupe    | 60000  | 2022-03-01     |
| 8      | Nissan     | Altima  | Sedan    | 26000  | 2022-02-10     |

-- 2. What is the total number of cars sold by each salesperson?
SELECT name AS salesperson,
        COUNT(car_id) AS num_of_cars_sold
FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
GROUP BY name
ORDER BY num_of_cars_sold DESC;

-- Sol2:
| Salesperson | Number of Cars Sold |
|-------------|----------------------|
| Tom Lee     | 6                    |
| John Smith  | 5                    |
| Emily Wong  | 5                    |
| Lucy Chen   | 4                    |

-- 3. What is the total revenue generated by each salesperson?
SELECT name AS salesperson,
        SUM(cost_$) AS total_revenue
FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
INNER JOIN cars ON sales.car_id = cars.car_id
GROUP BY name
ORDER BY total_revenue DESC;

-- Sol3:
| Salesperson | Total Revenue |
|-------------|---------------|
| Tom Lee     | 253000        |
| John Smith  | 181000        |
| Emily Wong  | 177000        |
| Lucy Chen   | 171000        |

-- 4. What are the details of the cars sold by each salesperson?
SELECT DISTINCT name AS salesperson,
        cars.*
FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
INNER JOIN cars ON sales.car_id = cars.car_id
ORDER BY salesperson, car_id;

-- Sol4:
| Salesperson | Car ID | Make       | Type    | Style     | Cost_$ | 
|-------------|--------|------------|---------|-----------|--------|
| Emily Wong  | 1      | Honda      | Civic   | Sedan     | 30000  |
| Emily Wong  | 2      | Toyota     | Corolla | Hatchback | 25000  |
| Emily Wong  | 4      | Chevrolet  | Camaro  | Coupe     | 36000  |
| Emily Wong  | 7      | Mercedes   | C-Class | Coupe     | 60000  |
| Emily Wong  | 8      | Nissan     | Altima  | Sedan     | 26000  |
| John Smith  | 1      | Honda      | Civic   | Sedan     | 30000  |
| John Smith  | 2      | Toyota     | Corolla | Hatchback | 25000  |
| John Smith  | 3      | Ford       | Explorer| SUV       | 40000  |
| John Smith  | 7      | Mercedes   | C-Class | Coupe     | 60000  |
| John Smith  | 8      | Nissan     | Altima  | Sedan     | 26000  |
| Lucy Chen   | 2      | Toyota     | Corolla | Hatchback | 25000  |
| Lucy Chen   | 4      | Chevrolet  | Camaro  | Coupe     | 36000  |
| Lucy Chen   | 5      | BMW        | X5      | SUV       | 55000  |
| Tom Lee     | 1      | Honda      | Civic   | Sedan     | 30000  |
| Tom Lee     | 2      | Toyota     | Corolla | Hatchback | 25000  |
| Tom Lee     | 3      | Ford       | Explorer| SUV       | 40000  |
| Tom Lee     | 5      | BMW        | X5      | SUV       | 55000  |
| Tom Lee     | 6      | Audi       | A4      | Sedan     | 48000  |

-- 5. What is the total revenue generated by each car type?
SELECT cars.type,
        SUM(cost_$) AS total_revenue
FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
GROUP BY cars.type
ORDER BY total_revenue DESC;

--Sol5:
| Type       | Total Revenue |
|------------|---------------|
| X5         | 220000        |
| C-Class    | 120000        |
| Corolla    | 100000        |
| Civic      | 90000         |
| Explorer   | 80000         |
| Camaro     | 72000         |
| Altima     | 52000         |
| A4         | 48000         |

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
WITH filtered_sales AS (
    SELECT car_id
    FROM sales
    WHERE salesman_id IN (SELECT salesman_id FROM salespersons WHERE name = 'Emily Wong')
        AND EXTRACT(YEAR FROM purchase_date) = 2021
)
SELECT DISTINCT cars.*
FROM cars
WHERE car_id IN (SELECT car_id FROM filtered_sales)
ORDER BY car_id;

-- Sol6:
| Car ID | Make       | Type    | Style     | Cost_$ |
|--------|------------|---------|-----------|--------|
| 2      | Toyota     | Corolla | Hatchback | 25000  |
| 4      | Chevrolet  | Camaro  | Coupe     | 36000  |

-- 7. What is the total revenue generated by the sales of hatchback cars?
WITH hatchback_cars AS (
    SELECT car_id, cost_$
    FROM cars
    WHERE style = 'Hatchback'
)
SELECT SUM(cost_$) AS total_revenue_hatchback_cars
FROM sales
INNER JOIN hatchback_cars ON sales.car_id = hatchback_cars.car_id;

-- Sol7:
| total_revenue_hatchback_cars |
|------------------------------|
| 100000                       |

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT SUM(cost_$) AS total_revenue_SUV_2022
FROM cars
WHERE car_id IN (SELECT car_id FROM sales WHERE EXTRACT(YEAR FROM purchase_date) = 2022)
    AND style = 'SUV';

-- Sol8:
| total_revenue_SUV_2022 |
|------------------------|
| 95000                  |

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
WITH best_salesman_2023 AS (
    SELECT salesman_id,
    COUNT(car_id) AS num_of_cars_sold_2023
    FROM sales
    WHERE EXTRACT(YEAR FROM purchase_date) = 2023
    GROUP BY salesman_id
    ORDER BY num_of_cars_sold_2023 DESC
    LIMIT 1
)
SELECT name AS salesperon,
    city
FROM salespersons
WHERE salesman_id IN (SELECT salesman_id FROM best_salesman_2023);

-- Sol9:
| salesperson | city    |
|-------------|---------|
| Tom Lee     | Seattle |

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
WITH sales_2022 AS (
    SELECT salesman_id,
        car_id
    FROM sales
    WHERE EXTRACT(YEAR FROM purchase_date) = 2022
),
cars_2022 AS (
    SELECT salesman_id,
        SUM(cost_$) AS total_revenue
    FROM sales_2022
    LEFT JOIN cars ON sales_2022.car_id = cars.car_id
    GROUP BY salesman_id
    ORDER BY total_revenue DESC
    LIMIT 1
)
SELECT name AS salesperson,
    age
FROM salespersons
WHERE salesman_id IN (SELECT salesman_id FROM cars_2022);

-- Sol10:
| salesperson | age     |
|-------------|---------|
| Emily Wong  | 35      |
