-- Challenge 3 - Customer Insights

-- INTRO
/*
You are a Customer Insights Analyst for 'The General Store'
Can you analyse the following tables to find out crucial information about your customers to provide to your marketing team?
*/

-- Query country table
SELECT *
FROM country;

-- Query customers table
SELECT *
FROM customers;

-- Query orders table
SELECT *
FROM orders;

-- Query products table
SELECT *
FROM products;

-- Query baskets table
SELECT *
FROM baskets;

-- QUESTIONS

-- 1. What are the names of all the countries in the country table?
SELECT DISTINCT(country_name)
FROM country;

-- 2. What is the total number of customers in the customers table?
SELECT COUNT(customer_id)
FROM customers;

-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
SELECT ROUND(AVG(age), 0) AS average_age
FROM customers
WHERE can_email = 'yes';

-- 4. How many orders were made by customers aged 30 or older?
SELECT COUNT(order_id) AS num_of_orders_by_customers_aged_30_or_older
FROM orders
LEFT JOIN customers ON orders.customer_id = customers.customer_id
WHERE age >= 30;

-- 5. What is the total revenue generated by each product category?
SELECT category,
    SUM(price) AS total_revenue_generated
FROM baskets
INNER JOIN products ON baskets.product_id = products.product_id
GROUP BY category
ORDER BY total_revenue_generated DESC;

-- 6. What is the average price of products in the 'food' category?
SELECT ROUND(AVG(price), 2) AS average_price_food_category_products
FROM products
WHERE category = 'food';

-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
SELECT sales_channel,
    COUNT(order_id) AS order_counts
FROM orders
GROUP BY sales_channel
ORDER BY order_counts;

-- 8. What is the date of the latest order made by a customer who can receive marketing emails?
SELECT MAX(date_shop)
FROM orders
WHERE customer_id IN (
    SELECT customer_id
    FROM customers
    WHERE can_email = 'yes'
    );

-- 9. What is the name of the country with the highest number of orders?
SELECT country_name,
    COUNT(order_id) AS num_of_orders
FROM orders
INNER JOIN country ON orders.country_id = country.country_id
GROUP BY country_name
ORDER BY num_of_orders DESC
LIMIT 1;

-- 10. What is the average age of customers who made orders in the 'vitamins' product category?
WITH vitamin_order AS (
    SELECT DISTINCT(order_id)
    FROM baskets
    WHERE product_id IN (
        SELECT product_id
        FROM products
        WHERE category = 'vitamins'
    )
),

customers_order_vitamins AS (
    SELECT customer_id
    FROM orders
    WHERE order_id IN (
        SELECT order_id 
        FROM vitamin_order
        )
)

SELECT ROUND(AVG(age), 2) AS avg_age_of_customers_ordering_vitamin_products
FROM customers
WHERE customer_id IN (
    SELECT customer_id
    FROM customers_order_vitamins
);

