-- Challenge 3 - Customer Insights

-- QUESTIONS

-- 1. What are the names of all the countries in the country table?
SELECT DISTINCT(country_name)
FROM country;

-- Sol1:
| country_name |
|--------------|
| China        |
| UK           |
| USA          |

-- 2. What is the total number of customers in the customers table?
SELECT COUNT(customer_id) AS num_of_customers
FROM customers;

-- Sol2:
| num_of_customers |
|------------------|
| 8                |

-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
SELECT ROUND(AVG(age), 0) AS average_age
FROM customers
WHERE can_email = 'yes';

-- Sol3:
| average_age |
|-------------|
| 37          |

-- 4. How many orders were made by customers aged 30 or older?
SELECT COUNT(order_id) AS num_of_orders_by_customers_aged_30_or_older
FROM orders
LEFT JOIN customers ON orders.customer_id = customers.customer_id
WHERE age >= 30;

-- Sol4:
| num_of_orders_by_customers_aged_30_or_older |
|---------------------------------------------|
| 3                                           |

-- 5. What is the total revenue generated by each product category?
SELECT category,
    SUM(price) AS total_revenue_generated
FROM baskets
INNER JOIN products ON baskets.product_id = products.product_id
GROUP BY category
ORDER BY total_revenue_generated DESC;

-- Sol5:
| category | total_revenue_generated |
|----------|-------------------------|
| vitamins | 66.93                   |
| sports   | 37.47                   |
| food     | 25.74                   |

-- 6. What is the average price of products in the 'food' category?
SELECT ROUND(AVG(price), 2) AS average_price_food_category_products
FROM products
WHERE category = 'food';

-- Sol6:
| average_price_food_category_products |
|--------------------------------------|
| 3.44                                 |

-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
SELECT sales_channel,
    COUNT(order_id) AS order_counts
FROM orders
GROUP BY sales_channel
ORDER BY order_counts;

-- Sol7:
| sales_channel | order_counts |
|---------------|--------------|
| online        | 3            |
| retail        | 5            |

-- 8. What is the date of the latest order made by a customer who can receive marketing emails?
SELECT MAX(date_shop) AS latest_order_date
FROM orders
WHERE customer_id IN (
    SELECT customer_id
    FROM customers
    WHERE can_email = 'yes'
    );

-- Sol8:
| latest_order_date |
|-------------------|
| 2023-02-02        |

-- 9. What is the name of the country with the highest number of orders?
SELECT country_name,
    COUNT(order_id) AS num_of_orders
FROM orders
INNER JOIN country ON orders.country_id = country.country_id
GROUP BY country_name
ORDER BY num_of_orders DESC
LIMIT 1;

-- Sol9:
| country_name | num_of_orders |
|--------------|---------------|
| UK           | 5             |

-- 10. What is the average age of customers who made orders in the 'vitamins' product category?
WITH vitamin_order AS (
    SELECT DISTINCT(order_id)
    FROM baskets
    WHERE product_id IN (
        SELECT product_id
        FROM products
        WHERE category = 'vitamins'
    )
),

customers_order_vitamins AS (
    SELECT customer_id
    FROM orders
    WHERE order_id IN (
        SELECT order_id 
        FROM vitamin_order
        )
)

SELECT ROUND(AVG(age), 2) AS avg_age_of_customers_ordering_vitamin_products
FROM customers
WHERE customer_id IN (
    SELECT customer_id
    FROM customers_order_vitamins
);

-- Sol10:
| avg_age_of_customers_ordering_vitamin_products |
|-----------------------------------------------|
| 32.50                                         |

